# Practice Numpy

In [1]:
import numpy as np

In [5]:
# Create array using numpy 
arr = np.array([1,2,3,4,5]) 
print(arr)
print(type(arr))
print(arr.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
# Reshape to 2 dimensions
arr2  = np.array([6,7,8,9,10])
arr2.reshape(1,5) # 1 row , 5 columns 

array([[ 6,  7,  8,  9, 10]])

In [11]:
arr3 = np.array([[23,54,65,35,654],[1,2,3,4,5]]) 
print(arr3.shape)
print(arr3)

(2, 5)
[[ 23  54  65  35 654]
 [  1   2   3   4   5]]


In [19]:
# arange() 
np.arange(3,31,3).reshape(10,1)

array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18],
       [21],
       [24],
       [27],
       [30]])

In [21]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
# Identity matrix 
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# Attributes 
ones_arr = np.ones((5,5),dtype=int)
print(ones_arr.ndim)
print("Size of array : ",ones_arr.size)
print("Data type : ",ones_arr.dtype)
print("Item size (in bytes) : ",ones_arr.itemsize)

2
Size of array :  25
Data type :  int64
Item size (in bytes) :  8


In [ ]:
# Numpy vectorized operations
new_arr = np.array([1,2,3,4,5])
new_arr2 = np.array([10,20,30,40,50])

# Element wise addition 
print("Addition : ",new_arr+new_arr2)

# Element wise subtraction
print("Subtraction : ",new_arr2-new_arr)

# Element wise multiplication
print("Multiplication : ",new_arr2*new_arr)

# Element wise Division
print("Subtraction : ",new_arr2/new_arr)

Addition :  [11 22 33 44 55]
Subtraction :  [ 9 18 27 36 45]


In [43]:
# Universal functions 
an_arr= np.array([19,34,52,67,3])

# Print square root of entire array 
print(np.sqrt(an_arr))

# Exponential 
print(np.exp(an_arr))

# natural log 
print(np.log(an_arr))


[4.35889894 5.83095189 7.21110255 8.18535277 1.73205081]
[1.78482301e+08 5.83461743e+14 3.83100800e+22 1.25236317e+29
 2.00855369e+01]
[2.94443898 3.52636052 3.95124372 4.20469262 1.09861229]


In [55]:
# Array slicing and indexing operation 

zarray = np.array([[1,2,3,4],[5,6,7,8],[9,10,11, 12]])
print(zarray)
print("\n")

print(zarray[1:,2:])
print("\n")


print(zarray[0:2,2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[[ 7  8]
 [11 12]]


[[3 4]
 [7 8]]


In [57]:
# Modify array elements 
zarray[0,0] = 100 
print(zarray)

zarray[1:] = 100
print(zarray)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [2]:
# Problem Statement 
import numpy as np 

In [7]:
class_A = np.array([[78,92,77,84,85],
                    [92,88,89,80,75],
                    [57,67,70,69,70],
                    [80,77,72,59,70],
                    [90,95,88,89,85],
                    [50,65,67,89,90]])

class_B = np.array([[90,89,95,99,87],
                    [88,90,75,70,90],
                    [67,70,56,50,88],
                    [77,76,75,80,85],
                    [59,50,65,78,50],
                    [90,96,90,92,98]])

print("Class A : \n",class_A)
print("\n")
print("Class B : \n",class_B)

Class A : 
 [[78 92 77 84 85]
 [92 88 89 80 75]
 [57 67 70 69 70]
 [80 77 72 59 70]
 [90 95 88 89 85]
 [50 65 67 89 90]]


Class B : 
 [[90 89 95 99 87]
 [88 90 75 70 90]
 [67 70 56 50 88]
 [77 76 75 80 85]
 [59 50 65 78 50]
 [90 96 90 92 98]]


In [ ]:
# Inspecting the dataset 
print("Dimensions of class A : ",class_A.ndim)
print("Dimensions of class B : ",class_A.ndim)


print("Size of class A : ",class_A.size)
print("Size of class B : ",class_B.size)


print("Size of class A : ",class_A.dtype)
print("Size of class B : ",class_B.dtype)


print("Size of class A : ",class_A.itemsize)
print("Size of class B : ",class_B.itemsize)

print("Shape of class A : ",class_A.shape)
print("Shape of class A : ",class_B.shape)

print("Sum of marks ",np.sum(class_A,axis=1))
print("Sum of marks ",np.average(class_A,axis=1))


Dimensions of class A :  2
Dimensions of class B :  2
Size of class A :  30
Size of class B :  30
Size of class A :  int64
Size of class B :  int64
Size of class A :  8
Size of class B :  8
Shape of class A :  (6, 5)
Shape of class A :  (6, 5)
Sum of marks  [416 424 333 358 447 361]
Sum of marks  [83.2 84.8 66.6 71.6 89.4 72.2]


In [27]:
# 30 rows and 1 columns 
class_A.reshape(5,6)


array([[78, 92, 77, 84, 85, 92],
       [88, 89, 80, 75, 57, 67],
       [70, 69, 70, 80, 77, 72],
       [59, 70, 90, 95, 88, 89],
       [85, 50, 65, 67, 89, 90]])

In [ ]:
class_A = np.array([[78,92,77,84,85],
                    [92,88,89,80,75],
                    [57,67,70,69,70],
                    [80,77,72,59,70],
                    [90,95,88,89,85],
                    [50,65,67,89,90]])

# Class A : 
#  [[78 92 77 84 85]
#  [92 88 89 80 75]
#  [57 67 70 69 70]
#  [80 77 72 59 70]
#  [90 95 88 89 85]
#  [50 65 67 89 90]]

print("=========Class A=========")

# Adding the marks of individual students 
total_scores_of_students_a = np.sum(class_A,axis=1)

# Converting the scores matrix into single columns to see student wise vertically 
flatten_a = total_scores_of_students_a.reshape(6,1) #6 rows and 1 column , each row represents a students marks
print("Total Scores per student : \n",flatten_a)

# From the total scores finding the student who has highest total score 
toppers_total_score_a = np.argmax(flatten_a) # this returns the index of student with higest total score
print("Total score of Topper : ",flatten_a[toppers_total_score_a])

Topper_A = flatten_a[toppers_total_score_a]

# Prints the scores of student who has the highest score in class af 
scores_of_topper_a = class_A[toppers_total_score_a]
print("Scores of Topper : ",scores_of_topper_a)

=========Class A=========
Total Scores per student : 
 [[416]
 [424]
 [333]
 [358]
 [447]
 [361]]
Total score of Topper :  [447]
Scores of Topper :  [90 95 88 89 85]


In [ ]:
class_B = np.array([[90,89,95,99,87],
                    [88,90,75,70,90],
                    [67,70,56,50,88],
                    [77,76,75,80,85],
                    [59,50,65,78,50],
                    [90,96,90,92,98]])

# Class B : 
#  [[90 89 95 99 87]
#  [88 90 75 70 90]
#  [67 70 56 50 88]
#  [77 76 75 80 85]
#  [59 50 65 78 50]
#  [90 96 90 92 98]]

#Adding the scores of all the students 
print("=========Class B=========")

# Adding the marks of individual students 
total_scores_of_students_b = np.sum(class_B,axis=1)

# Converting the scores matrix into single columns to see student wise vertically 
flatten_b = total_scores_of_students_b.reshape(6,1) #6 rows and 1 column , each row represents a students marks
print("Total Scores per student : \n",flatten_b)

# From the total scores finding the student who has highest total score 

toppers_total_score_b = np.argmax(flatten_b) # this returns the index of student with higest total score
print("Total score of Topper : ",flatten_b[toppers_total_score_b])


Topper_B = flatten_b[toppers_total_score_b]


# Prints the scores of student who has the highest score in class 
scores_of_topper_b = class_B[toppers_total_score_b]
print("Scores of Topper : ",scores_of_topper_b)

=========Class B=========
Total Scores per student : 
 [[460]
 [413]
 [331]
 [393]
 [302]
 [466]]
Total score of Topper :  [466]
Scores of Topper :  [90 96 90 92 98]


In [ ]:
if Topper_A > Topper_B: 
   difference = Topper_A-Topper_B
else: 
    difference = Topper_B-Topper_A

if Topper_A > Topper_B: 
    print(f"Student from class A has scored highest with score : {Topper_A} with difference of {difference}")
else: 
    print(f"Student from class B has scored highest with score : {Topper_B} with difference of {difference}")

Student from class B has scored highest with score : [466] with difference of [19]
