# Numpy Assessments

In [2]:
# 1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

import numpy as np 
arr  = np.random.randint(1,21,size=(5,5))

print("Array : ")
print(arr)
print("\n")

arr[2:] = 1
print(arr)

Array : 
[[ 2 15 11  6  4]
 [ 9  5 20 17 12]
 [ 9 12  6 11 12]
 [ 6  3 15  9  4]
 [ 6  3  5 16 18]]


[[ 2 15 11  6  4]
 [ 9  5 20 17 12]
 [ 1  1  1  1  1]
 [ 1  1  1  1  1]
 [ 1  1  1  1  1]]


In [3]:
# 2. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

arr2 = np.random.randint(1,37 , size=(6,6))
print(arr2)
print("\n")
print(arr2[2:5,1:4])

[[31  3  5 22  6 13]
 [27  8 11 16 36 14]
 [ 5 22 28 30 14 16]
 [23  6 26 18 27 21]
 [25 13 11  5  4 29]
 [19 17 17 15  9 22]]


[[22 28 30]
 [ 6 26 18]
 [13 11  5]]


In [4]:
# 3. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

arr3= np.random.randint(1,30,size=(5,5))
print(arr3)
print("\n")
bordered_elements = np.concatenate((arr3[0,:],arr3[-1,:],arr3[:,0],arr3[:,-1]))
print("Borders : \n")
print(bordered_elements)


[[26 25 20 24  5]
 [ 5 16 15 24 26]
 [ 6  9  8 13 19]
 [25  2 22 11  2]
 [ 2 17 23 11 27]]


Borders : 

[26 25 20 24  5  2 17 23 11 27 26  5  6 25  2  5 26 19  2 27]


In [5]:
# 4. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

arr4 = np.arange(1,13).reshape((3,4))
arrn = np.arange(1,13).reshape((3,4))
print("Element wise addition")
print(arr4+arrn)

print("Element wise subtraction ")
print(arr4-arrn)

print("Element wise multiplication : ")
print(arr4*arrn)

print("Element wise division ")
print(arr4/arrn)

Element wise addition
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Element wise subtraction 
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Element wise multiplication : 
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Element wise division 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
# 5. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

arr5 = np.arange(1,17).reshape((4,4))
row_wise_sum = np.sum(arr5,axis=0)
col_wise_sum = np.sum(arr5,axis=1)
print("Original Array : \n")
print(arr5)
print(" ")
print("Row Wise sum is : ",row_wise_sum)
print("Column Wise sum is : ",col_wise_sum)

Original Array : 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
 
Row Wise sum is :  [28 32 36 40]
Column Wise sum is :  [10 26 42 58]


In [13]:
# 6. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

arr6 = np.arange(1,26).reshape((5,5))
mean = np.mean(arr6)
median =  np.median(arr6)
std = np.std(arr6)
variance = np.var(arr6)

print("Mean is : ",mean)
print("Median is : ",median)
print("Standard Deviation : ",std)
print("Variance : ",variance)

Mean is :  13.0
Median is :  13.0
Standard Deviation :  7.211102550927978
Variance :  52.0


In [ ]:
# 7. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

# Calculate the mean of array 
# calculate the standard deviation 
# Subtract arr by mean and then divide the result by standard deviation

# Normalize the array 
arr7 = np.arange(1,10).reshape((3,3))
mean  = np.mean(arr7)
standard_deviation = np.std(arr7)
normalized_arr7 = (arr7 - mean) / standard_deviation

print("Normalized Array : \n")
print(normalized_arr7)




Normalized Array : 

[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [23]:
# 8. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting. (This is broadcasting)

# Broadcasting 
# Broadcasting allows NumPy to perform element-wise operations 
# between arrays of different shapes by logically expanding the 
# smaller array to match the shape of the larger one — without copying data.
# Dimensions are compatible if they are equal or one of them is 1.



arr8 = np.arange(1,10).reshape((3,3))
one_D_arr = np.arange(1,4)

# Here one_D_arr is 1D array , so numpy will logically stretch this 1D (1row array ) array into 3 rows and then will add with the main array which also have 3 rows and 3 cols .
# Broadcasting is a logical concept , the numpy is not a concept.
new_arr = arr8+one_D_arr
print(arr8)
print(" \n ")
print(new_arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
 
 
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [28]:
# 9. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

arr9 = np.arange(1,17).reshape((4,4))
row_arr = np.arange(1,5)

b_array = arr9-row_arr
print("Original array : ")
print(arr9)
print(" ")
print("Row Array : ")
print(row_arr)
print(" ")

print("Broadcasted Array ")
print(b_array)


Original array : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
 
Row Array : 
[1 2 3 4]
 
Broadcasted Array 
[[ 0  0  0  0]
 [ 4  4  4  4]
 [ 8  8  8  8]
 [12 12 12 12]]


In [29]:

# 10. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

arr10 = np.arange(1,10).reshape((3,3))
print("Original matrix ")
print(arr10)

print(" ")

determinat = np.linalg.det(arr10)
print("Determinant : ")
print(determinat)

print(" ")
inverse = np.linalg.inv(arr10)
print("Inverse : ")
print(inverse)

print(" ")

eigenvalues = np.linalg.inv(arr10)
print("Eigenvalues : ")
print(inverse)



Original matrix 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
 
Determinant : 
-9.51619735392994e-16
 
Inverse : 
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
 
Eigenvalues : 
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [31]:
# 11. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform dot product of these arrays.

arr11 = np.arange(1,7).reshape((2,3))
arrm = np.arange(1,7).reshape((3,2))

dot_product = np.dot(arr11,arrm)

print("Orignal matrix : ")
print(arr11)
print(" ")

print("Second matrix : ")
print(arrm)
print(" ")

print("Dot product : ")
print(dot_product)

Orignal matrix : 
[[1 2 3]
 [4 5 6]]
 
Second matrix : 
[[1 2]
 [3 4]
 [5 6]]
 
Dot product : 
[[22 28]
 [49 64]]


In [34]:
# 12. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

arr12  = np.arange(1,10).reshape((3,3))

print("Original array : ")
print(arr12)

print(" ")

print("Reshaped array : ")
reshaped_array1 = arr12.reshape((1,9))
print(reshaped_array1)

print(" ")

print("Reshaped array : ")
reshaped_array2 = arr12.reshape((9,1))
print(reshaped_array2)

Original array : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
 
Reshaped array : 
[[1 2 3 4 5 6 7 8 9]]
 
Reshaped array : 
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [38]:
# 13. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

arr13 = np.arange(1,26,1).reshape((5,5))
print(arr13)
print(" ")


flatten_a = arr13.flatten()
print("Flatten A ")
print(flatten_a)
print(" ")

reshaped_array_13  = flatten_a.reshape((5,5))
print("Reshaped Array : ")
print(reshaped_array_13)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
 
Flatten A 
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
 
Reshaped Array : 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
# 14. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
import numpy as np 
array14= np.arange(1,26,1).reshape((5,5))

print("original array : ")
print(array14)
print(" ")
corners = array14[[0,0,-1,-1],[0,-1,0,-1]]
# above line will be seen as 


# [[0,0,-1,-1] ,  [0,-1,0,-1]]
# [first list] , [second list]
# arr[0][0]   # first row , first corner 
# arr[0][-1]  # first row , last corner 
# arr[-1][0]  # last row , first corner
# arr[-1][-1] # last row , last corner 

print("Corner elements : ")
print(corners)

original array : 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
 
Corner elements : 
[ 1  5 21 25]


In [4]:
# 15. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing , In the array , all the elements greater than 10 should be replaced with 10 

arr15 = np.arange(1,17).reshape((4,4))
print(arr15)

arr15[ arr15 > 10 ] = 10 # Elements > 10 will be replaced by 10 

print(" ")
print(arr15)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 10 10]
 [10 10 10 10]]


In [16]:
# 1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

data = [('name','U10') , ('age','i4'), ('weight','f4')]

new_data = np.array([('Alice',25,55.5) , ('Bob',39,85.3) , ('Charlie', 20 , 65.2)],dtype=data)

print("Original data : ")
print(new_data)

sorted_data = np.sort(new_data,order='age')
print("Sorted data ")
print(sorted_data)

Original data : 
[('Alice', 25, 55.5) ('Bob', 39, 85.3) ('Charlie', 20, 65.2)]
Sorted data 
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 39, 85.3)]


In [ ]:
# 2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.